# Dev properties using H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:laundry_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# reduce startup logging
logging.level.org.hibernate.SQL=DEBUG

# Do not run schema.sql (we rely on Hibernate DDL)
spring.sql.init.mode=never

# Disable devtools restart to avoid immediate shutdown during dev
spring.devtools.restart.enabled=false