/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                // Using standard Tailwind colors for Soft Palette: Sky Blue, White, Slate Gray
                // We can extend specific tokens if needed, but standard palette often suffices.
                // sky-50 to sky-900, slate-50 to slate-900 are generated by default.
            }
        },
    },
    plugins: [],
}
